### ISSUE TITLE
Console.OnMessageReceived Event

### ISSUE THREAD

**Issue by isolatedperson** [SpaceMadness/lunar-unity-console#100]
Hi there,

Can you please provide a OnMessageRecieve Callback so when console receive any message we can trigger something on Unity side on Pro version.

Thanks

**Comment by weeeBox** [comment]
Sure

**Comment by isolatedperson** [comment]
@weeeBox thank you very much for your quick response, can you give a rough idea when can we see it?

**Comment by weeeBox** [comment]
If you just need to capture the log event you can use a built-in Unity API: https://docs.unity3d.com/ScriptReference/Application-logMessageReceived.html

**Comment by isolatedperson** [comment]
@weeeBox thank you very much, this does solve the issue 💃
