### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Droid22** [SpaceMadness/lunar-unity-console#102]
`NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Editor.get_referenceTargetIndex () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:162)
UnityEditor.Experimental.AssetImporters.AssetImporterEditor.get_referenceTargetIndex () (at C:/buildslave/unity/build/Editor/Mono/ImportSettings/AssetImporterEditor.cs:25)
UnityEditor.Editor.get_target () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:148)
UnityEditor.Experimental.AssetImporters.AssetImporterEditor.OnDisable () (at C:/buildslave/unity/build/Editor/Mono/ImportSettings/AssetImporterEditor.cs:84)
UnityEditor.AssetDatabase:DeleteAsset(String)
LunarConsoleEditorInternal.Autorun:CleanLegacyFiles() (at Assets/LunarConsole/Editor/Autorun.cs:64)
LunarConsoleEditorInternal.Autorun:.cctor() (at Assets/LunarConsole/Editor/Autorun.cs:54)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()`

This happens while running in the editor.

**Comment by weeeBox** [comment]
Sorry for the issue. I'll take a look

**Comment by weeeBox** [comment]
Fixed in 1.5.2
