### ISSUE TITLE
Console blocks app after minimize/restore

### ISSUE THREAD

**Issue by yangicher** [SpaceMadness/lunar-unity-console#104]
1. Launch app with enabled Lunar
2. Minimize/restore app

Device mode: Nexus 5 
Android 6.0
Unity version 2017.2.0f3
Lunar Version: 1.5.2 

Lunar settings:
exception warning - true
trans log overlay - true
sort actions - true
sort variables - true
email -
capacity 4096
trim 512
gesture - swipe down
remove rich text tags - false

**Comment by weeeBox** [comment]
Hi @yangicher, it's a known bug since Unity 5.6.x. I haven't found a workaround yet.

**Comment by weeeBox** [comment]
@yangicher, I've prepared a workaround. Should we available on the asset store in the next couple of days (hope Christmas won't affect it too long)

**Comment by weeeBox** [comment]
@yangicher, you can download the patch [here](https://github.com/SpaceMadness/lunar-unity-console-patches/raw/master/lunar-console-patch-1.5.3.unitypackage)

**Comment by weeeBox** [comment]
@yangicher, did it solve your issue?

**Comment by yangicher** [comment]
@weeeBox no(

**Comment by weeeBox** [comment]
@yangicher, try to completely remove the plugin and install the latest version from the Asset Store
