### ISSUE TITLE
Settings Screen not working on Android in Unity 2018.x

### ISSUE THREAD

**Issue by re-cheid** [SpaceMadness/lunar-unity-console#113]
The settings screen is displayed black on Andriod when built with Unity 2018.x
With Unity 2017.3 it works as expected.

I'm using Lunar Mobile Console - PRO v1.5.3
Tested with OnePlus One (Android 6) and Asus ZenPhone AR (Android 7)

**Comment by weeeBox** [comment]
Hi @re-cheid,

Would you be able to provide some additional info?
- Scripting Backend (Mono/IL2CPP/.NET)
- Host OS version

**Comment by re-cheid** [comment]
Hey @weeeBox 

I tried with all scripting backends, same result. Seems like only the background color of the Settings screen is black.
I am working with Unity on Windows 10.
This only happens with Unity 2018.x

Here's a screenshot:
![image](https://user-images.githubusercontent.com/25147494/45153092-20b8d500-b1d3-11e8-9fb2-e16c2d9a606d.png)

**Comment by weeeBox** [comment]
Thanks, @re-cheid.

Seems like something overrides the default theme. Can you list all the android plugins from you project?

**Comment by re-cheid** [comment]
This is a clean Unity project, which i created for evaluating this error, only LunarConsole in it.

**Comment by weeeBox** [comment]
Hi @senkal,

Actions/variables use the same theming as log view. I'm looking at the issue right now.

**Comment by senkal** [comment]
Hi @weeeBox 

Thank you for fast update.
Hopefully you will be able to resolve the issue.

**Comment by weeeBox** [comment]
Fixed in 1.5.5 (update pending)

**Comment by weeeBox** [comment]
Path file [available](https://github.com/SpaceMadness/lunar-unity-console-patches/blob/master/lunar-console-full-1.5.5-patch.unitypackage?raw=true)
