### ISSUE TITLE
Does Not Swipe Up and Open Unity 2018.1 Android Build

### ISSUE THREAD

**Issue by sinhadanish** [SpaceMadness/lunar-unity-console#114]

**Comment by weeeBox** [comment]
Hey @sinhadanish,

Would you be able to provide some more info as described in the [Troubleshooting](https://github.com/SpaceMadness/lunar-unity-console/wiki/Troubleshooting#before-you-start) guide?

**Comment by weeeBox** [comment]
Hey @sinhadanish,

Do you have any updates on this? I've tried Unity versions and devices - still can't reproduce. Can you also look at this [guide](https://github.com/SpaceMadness/lunar-unity-console/wiki/Troubleshooting#swipe-gesture-does-not-open-the-console)?
