### ISSUE TITLE
Variables not found (but quick fix)

### ISSUE THREAD

**Issue by kinoc** [SpaceMadness/lunar-unity-console#125]

**Comment by kinoc** [comment]
Sorry about that empty entry. After the upgrade to 1.5.6 my projects variables stopped displaying. 
Changing the following code in LunarConsole.cs@345 caused them to reappear. There may be a better way, but it fixes it for me for now .
      
 private static IList<Assembly> ListAssemblies() {
            // for now only list the current assembly
            Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
            if (assemblies != null) return assemblies;
            return new Assembly[] { Assembly.GetExecutingAssembly() };
       }

**Comment by weeeBox** [comment]
Hey @kinoc,

Sorry about the issue. Which Unity version do you use?

**Comment by kinoc** [comment]
No problem, I remember seeing something like it before. Other members pushed the upgrade and I just had to re-search the issue. 
I am using 2018.3.0f2 on Win 10 building for Android testing on a Samsung S8 . It shows up in play mode in my editor.

**Comment by weeeBox** [comment]
Fixed in [1.5.7](https://github.com/SpaceMadness/lunar-unity-console/releases/tag/1.5.7)
