### ISSUE TITLE
Lunar uses variables cache

### ISSUE THREAD

**Issue by senkal** [SpaceMadness/lunar-unity-console#127]
Hi,
I am not sure if somebody else encounter this "problem" but I couldn't find anything in the docs or issues.
In general, looks like Lunar Console caches user variables in a way which is confusing, to me at least.

What do I mean?
1. Create Lunar variable "playerSpeed".
2. Everything works I can edit it on my Android, awesome.
3. For any reason I don't want to expose this variable to Lunar console any more, so I remove it from variables and callbacks code.
4. I deploy modified Lunar script, and somehow, variables are still set from last Lunar values on device. Even if it's not in the Lunar variables/callbacks code any more it is still used, don't know it works. Probably something with serializing.
5. What helps is clearing app cache on Android, this removes this "caching" effect.

I spent some time trying to figure it out why some parameters are changed even if they are not in the Lunar console code and I think that is the case.

Does it make sense at all?

**Comment by weeeBox** [comment]
Hey @senkal,

Sorry for the issue. I'll take a closer look.

**Comment by senkal** [comment]
Thanks @weeeBox for fast answer.
If you won't be able to replicate the issue let me know, will try to be useful as much as possible.
Good luck.

**Comment by weeeBox** [comment]
Thanks! I really appreciate that!

**Comment by senkal** [comment]
Hi @weeeBox 
My fault, didn't describe it well.
So the removed variables are removed from UI, that is not the problem I encounter.
The problem is, even if variables are no in UI and not in the code, they are still somehow applied.

Before you check this give me a week or so will try to create a simple project where this can be replicated.

**Comment by weeeBox** [comment]
Hey @senkal,

I'm not 100% sure about this part 

> they are still somehow applied

**Comment by senkal** [comment]
Agree, looks really weird.
I am not sure how this could work.
Need some time to separate the issue.

**Comment by weeeBox** [comment]
More information would definitely help troubleshooting!

**Comment by senkal** [comment]
So in the end it didn't make sense.
After more digging I think I found the issue and wasn't strictly related to Lunar Console, more to invalid way I used it.
I mixed some Awake/Start order in my project.
I think it's ok to close this issue, in the end there was no issue to begin with.

**Comment by weeeBox** [comment]
Glad you were able to figure this out! Don't forget to rate and review the plugin if you find it useful!

**Comment by senkal** [comment]
@weeeBox I already did, so don't worry :)
