### ISSUE TITLE
Option to disable Update check/Tracking

### ISSUE THREAD

**Issue by brzGatsu** [SpaceMadness/lunar-unity-console#134]
Can we please have an option to disable the update check in Autorun.cs (costs time to enter playmode)? Also an option to disable tracking would be nice (data privacy).

**Comment by oddgames-david** [comment]
+1 currently breaking my builds due to dns issues.

**Comment by weeeBox** [comment]
Fixed in 1.6.2

- Use `LUNAR_CONSOLE_ANALYTICS_DISABLED` to disable tracking
- Use `LUNAR_CONSOLE_UPDATER_DISABLED ` to disable updater
