### ISSUE TITLE
App crashes on iOS

### ISSUE THREAD

**Issue by mleenhardt** [SpaceMadness/lunar-unity-console#140]
We're seeing a crash on an iPhone 8+ running iOS 11.4. We're using IL2CPP, 2018.3.0f2 and Lunar Console 1.6.

1- Have the log overlay enabled
2- Swipe down and open the console
3- Disable all 3 log types (debug/info, warning, error/assert/exception) by taping on each icon on the top right
4- Close the console, do something that causes a log line of any kind to be written
---> The app crashes

**Comment by weeeBox** [comment]
@mleenhardt, sorry about the issue. I'm working on the fix.

**Comment by weeeBox** [comment]
@mleenhardt, I've uploaded a patch file which fixes the crash: [lunar-console-full-1.6.1-patch.unitypackage](https://github.com/SpaceMadness/lunar-unity-console-patches/blob/master/lunar-console-full-1.6.1-patch.unitypackage?raw=true). I'll submit an update to the asset store later today.

**Comment by weeeBox** [comment]
Fixed in 1.6.1
