### ISSUE TITLE
Errors on iOS build Unity 2019.3beta

### ISSUE THREAD

**Issue by novavision** [SpaceMadness/lunar-unity-console#149]
After migrating to 2019.3 beta build the app in XCode I get these errors:

>`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CSSearchableItem", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "___lunar_console_destroy", referenced from:
      _PlatformIOS___lunar_console_destroy_m114FF77F0B6C0406EE23823E9DF73FA24713B2B1 in Assembly-CSharp8.o
      _PlatformIOS_Destroy_m212E1231F3D661AAC685C133619F09D83425F69B in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_destroy_m114FF77F0B6C0406EE23823E9DF73FA24713B2B1)
  "_OBJC_CLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_CLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
  "___lunar_console_action_unregister", referenced from:
      _PlatformIOS___lunar_console_action_unregister_m4B6755A00CA458A6BD7536E7B40A36BE2D220440 in Assembly-CSharp8.o
      _PlatformIOS_OnActionUnregistered_mACB6B2E72D32AEDC1378CE954FBDE0F299D638AB in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_action_unregister_m4B6755A00CA458A6BD7536E7B40A36BE2D220440)
  "___lunar_console_action_register", referenced from:
      _PlatformIOS___lunar_console_action_register_m6115B49F76CFFD779DC1117CAE8D520206D928BF in Assembly-CSharp8.o
      _PlatformIOS_OnActionRegistered_m3F441380DF418E4E22C4316FC37C4442A6F4498B in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_action_register_m6115B49F76CFFD779DC1117CAE8D520206D928BF)
  "___lunar_console_hide", referenced from:
      _PlatformIOS___lunar_console_hide_mA1E2CDE2625952F0594D1427FF2D369588C5FB36 in Assembly-CSharp8.o
      _PlatformIOS_HideConsole_m1A8A5D1A2497E99C3627A9FD1D260D17BD0B33DF in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_hide_mA1E2CDE2625952F0594D1427FF2D369588C5FB36)
  "_OBJC_CLASS_$_CSSearchableIndex", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "___lunar_console_clear", referenced from:
      _PlatformIOS___lunar_console_clear_mD50B0E9F448BBD2578EEF891D2B38DEBF2B6D328 in Assembly-CSharp8.o
      _PlatformIOS_ClearConsole_m33B458A9F453FC6F9EB2315A0C5FD660885C2D71 in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_clear_mD50B0E9F448BBD2578EEF891D2B38DEBF2B6D328)
  "___lunar_console_cvar_register", referenced from:
      _PlatformIOS___lunar_console_cvar_register_m71B24DBE5DC783EDF46666E51DAB8B41E4F72103 in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_cvar_register_m71B24DBE5DC783EDF46666E51DAB8B41E4F72103)
  "_OBJC_METACLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_METACLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
  "___lunar_console_initialize", referenced from:
      _PlatformIOS___lunar_console_initialize_mB2B5BC5CA4CB6E16EBAED0D2E2BFB01B6C2EAF00 in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_initialize_mB2B5BC5CA4CB6E16EBAED0D2E2BFB01B6C2EAF00)
  "___lunar_console_show", referenced from:
      _PlatformIOS___lunar_console_show_mBD272CD13226341EE9D14830AA98B1D9644DE511 in Assembly-CSharp8.o
      _PlatformIOS_ShowConsole_m0F2D48FCF9D606031B2D133DF3E8469D973674E9 in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_show_mBD272CD13226341EE9D14830AA98B1D9644DE511)
  "___lunar_console_cvar_update", referenced from:
      _PlatformIOS___lunar_console_cvar_update_mBB8B2DE189F1BF62F0F2EE1885026257E298A59D in Assembly-CSharp8.o
      _PlatformIOS_OnVariableUpdated_m6494D6C104303BC520BFF7A9214ECD4C46F3CFF6 in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_cvar_update_mBB8B2DE189F1BF62F0F2EE1885026257E298A59D)
  "___lunar_console_log_message", referenced from:
      _PlatformIOS___lunar_console_log_message_m3D66906E73F5AAA969C407D7E1ED4FBCDA853BD9 in Assembly-CSharp8.o
     (maybe you meant: _PlatformIOS___lunar_console_log_message_m3D66906E73F5AAA969C407D7E1ED4FBCDA853BD9)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

XCode version 11.1

**Comment by weeeBox** [comment]
Hey @novavision,

Sorry for the issue. I'll take a look at it asap

**Comment by weeeBox** [comment]
Hey @novavision,

Unity 2019.3 introduced breaking changes to `PBXProject`. Please, try this patch and let me know if it works for you.

[lunar-mobile-console-1.6.3-patch.unitypackage.zip](https://github.com/SpaceMadness/lunar-unity-console/files/3802257/lunar-mobile-console-1.6.3-patch.unitypackage.zip)

**Comment by novavision** [comment]
sorry, what should I do with these files from zip archive? [https://take.ms/SxXVr](image)
Using it as a package to import in Unity I got the message "All assets from this package already in a project"

**Comment by weeeBox** [comment]
Fixed in `1.6.3`

The patch file could be found [here](https://github.com/SpaceMadness/lunar-unity-console-patches/raw/master/lunar-console-full-1.6.3-patch.unitypackage)
