### ISSUE TITLE
How to use console on Unity 4.6.5?

### ISSUE THREAD

**Issue by Temka193** [SpaceMadness/lunar-unity-console#15]
I download and import from asset store.

Change 
```
                        Application.logMessageReceived += delegate(string message, string stackTrace, LogType type) {
                            platform.OnLogMessageReceived(message, stackTrace, type);
                        };

```

to 

```
                        Application.RegisterLogCallback(delegate(string message, string stackTrace, LogType type) {
                            platform.OnLogMessageReceived(message, stackTrace, type);
                        });

```

It gives this error:

> Can't init LunarConsole: java.lang.ClassNotFoundException: spacemadness.com.lunarconsole.console.ConsolePlugin

**Comment by weeeBox** [comment]
Hey there!

Sorry but the plugin is only supported on Unity 5.0.0 and later

**Comment by Temka193** [comment]
it does not really run on 4.6?

**Comment by weeeBox** [comment]
Can't tell for sure. There might be API incompatibility issues: haven't really tested it.

**Comment by Temka193** [comment]
I really need a console, can come up with something?
Or maybe there are analogs?

**Comment by weeeBox** [comment]
I'm traveling right now and have a very limited access to a laptop. Would take a look later but can't promise much: the backward compatibility with older Unity versions are not on the road map.

There're a few "competitor" products on the Asset Store - just look them up.

I would personally recommend to upgrade to the latest version of Unity. It might be a bit painful but would pay itself off in a long run.
