### ISSUE TITLE
Console opens automatically on app start, and reopen just after click "close"

### ISSUE THREAD

**Issue by novavision** [SpaceMadness/lunar-unity-console#156]
I am on Unity 2019.3b8 and experiencing the issue on Android build - when app starts console is showing up. Trying to close it clicking on "close" button, console opens again just after get hidden.
Android 10, Xiaomi K20Pro

**Comment by weeeBox** [comment]
Would you be able to debug the build from Android Studio? I haven't seen this before.
Place to put a breakpoint: https://github.com/SpaceMadness/lunar-unity-console/blob/master/Native/Android/LunarConsole/lunarConsole/src/main/java/spacemadness/com/lunarconsole/console/ConsolePluginImpl.java#L152. We need to know what triggers the code.

**Comment by novavision** [comment]
Sorry, but I can't setup gradle build on my end, it's full of errors and can setup it properly

**Comment by novavision** [comment]
Btw, just checked on iOS - everrything is fine there

**Comment by weeeBox** [comment]
No worries. Can you try to reproduce the issue on a "hello world" app with nothing but Lunar Console in it?

**Comment by novavision** [comment]
Will try, but I assume the reason is in VoxelBusters Native Plugin update. Somehow both assets worked fine together, but 2 days ago I had an error building for Android. Googling the solution I found the thread on their forum recommending to update these [files](https://drive.google.com/drive/folders/1eRXP_jYi-gBbrsYqBxuiMptM1rYnzkPf) for Unity 2019.3b.
May be you can find some conflict in GradlePostProcessor.cs? I am really not good with Android gradle projects.

**Comment by weeeBox** [comment]
So basically, when you updated the VoxelBusters Native Plugin - things broke, right? From the `GradlePostProcessor.cs` file I can see that they force the app to use AndroidX. It's very tricky to provide a compatibility between Support library (Lunar Mobile Console and Unity in general) and AndroidX (VoxelBusters). Unity does not support it yet. I'll take a look but can't guarantee a quick and easy fix.

**Comment by novavision** [comment]
@weeeBox please close this issue, it wasn't related to the asset itself.
