### ISSUE TITLE
Tengo un pequeño problema sobre grud

### ISSUE THREAD

**Issue by DicyLow** [SpaceMadness/lunar-unity-console#162]
![20200328_193859](https://user-images.githubusercontent.com/57680849/77837491-ea85d200-7137-11ea-9c28-b356416f0e7e.jpg)

**_
Error: Unknown FileSystem. Entering Rescue Mode ... Grud Rescue
_**

Quiero saber si alguien me puede ayuda con ese problema que me sucedes cada que intento instalar Android x86 en una laptop que tengo que un poco antigua. Y quiero sobrevivirla. 

Ayuda por favor Algun consejo.

**Comment by weeeBox** [comment]
Hello,

I believe you've opened an issue in a wrong repo
