### ISSUE TITLE
Feature request: colored logs, same as in Editor

### ISSUE THREAD

**Issue by novavision** [SpaceMadness/lunar-unity-console#165]
During last month I started to use colored `Debug.Log` in Unity, and really helps a lot when each game manager provide logs according to it's unique color.
As you know the code is something like that: 
`Debug.Log("<color=green>Notifications: {messsage}"`
Unfortunately Lunar Console doesn't support it and I see extended log without color convertation. 
Would be great to implement it.

**Comment by weeeBox** [comment]
Added to the roadmap.

**Comment by weeeBox** [comment]
Available in 1.7.0

**Comment by nntgam** [comment]
I have check it with version 1.8 on asset store but I can't show the color of the text. The log show like below
<b>TDEBUG►</b><color=#00cc99><b>InputLocked►</b></color><color=#ff5050><b>LOCKED</b></color>

**Comment by weeeBox** [comment]
@nntgam, can you try adding a closing `</color>` tag?

**Comment by nntgam** [comment]
![Screenshot_20210503-083548.png](https://user-images.githubusercontent.com/48884638/116834964-a8f11180-abea-11eb-9900-c1b78310a250.png)

**Comment by nntgam** [comment]
It still not working and not working with bold too

**Comment by nntgam** [comment]
> @nntgam, can you try adding a closing `</color>` tag?

Yes I have already put, this on auto format by github.
This is full log:
`<b>TDEBUG►</b><color=#00cc99><b>InputLocked►</b></color><color=#ff5050><b>LOCKED</b></color> Remove <b>DoBoardGenerateEffect</b> remain UILevelShowBegin`

**Comment by weeeBox** [comment]
@nntgam, can you double check if Rich Text Tags are enabled in the plugin?
<img width="278" alt="Screen Shot 2021-05-03 at 8 25 50 AM" src="https://user-images.githubusercontent.com/786644/116875672-4d725400-abe9-11eb-9da1-3f846ee98433.png">

**Comment by nntgam** [comment]
Thank you for your help,  but I don't know why the color is not correct. 
![image](https://user-images.githubusercontent.com/48884638/116878513-ab368880-ac49-11eb-9809-aa9c7ea64058.png)

**Comment by weeeBox** [comment]
@nntgam, this does not look right - can you try to use [color names](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html#supported-colors) and see if that works? Is this happening on iOS or Android?

**Comment by nntgam** [comment]
@weeeBox , Trying with color by name then it works. I'm using Android (Samsung S7).
Thank you for support

**Comment by weeeBox** [comment]
@nntgam, I'm re-opening the issue to investigate the hex-colors bug

**Comment by weeeBox** [comment]
@nntgam, fixed in 1.8.2
