### ISSUE TITLE
IOS build failure

### ISSUE THREAD

**Issue by Voresh** [SpaceMadness/lunar-unity-console#168]
When I am trying to build project with lunar with xcode I get this error: Build input file cannot be found: '/Volumes/_ProjectPathHere_/Assets/LunarConsole/Editor/iOS/Common/Console/Log/LUConsoleLogDetailsController.xib
I added LUNAR_CONSOLE_EXPORT_IOS_FILES define to unity project settings, but it doesnt work
Unity 2019.1.13
Xcode version 11.3.1
Lunar last version
I am build unity project on windows and then build XCode project on mac os

**Comment by weeeBox** [comment]
Hey @Voresh,

Can you check if the build folder contains "LunarConsole" folder?

**Comment by weeeBox** [comment]
Hey @Voresh, were you able to resolve the issue?
