### ISSUE TITLE
Dropdown View of List Variables

### ISSUE THREAD

**Issue by Mefodei** [SpaceMadness/lunar-unity-console#170]
in several cases most user friendly way: show only set of cheat variables values

**Comment by weeeBox** [comment]
Added to the roadmap. Thanks

**Comment by weeeBox** [comment]
Added in `1.8.0`.  
  
Usage:  
`public static readonly CEnumVar<MyEnum> myEnum = new CEnumVar<MyEnum>("My enum value", MyEnum.Two);`

**Comment by Mefodei** [comment]
Thx, that's sound great
