### ISSUE TITLE
lunar cause crash on ios 14.2

### ISSUE THREAD

**Issue by flankechen** [SpaceMadness/lunar-unity-console#187]
ipa crashes on ios 14.2 something like:

`Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, <RBSTerminateContext| domain:10 code:0x8BADF00D explanation:[application<com.sensetime.xzarnavi>:512] failed to terminate gracefully after 10.0s | ProcessVisibility: Unknown | ProcessState: Running | WatchdogEvent: process-exit | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 6.640 (user 6.640, system 0.000), 10% CPU", | "Elapsed application CPU time (seconds): 0.000, 0% CPU" | ) reportType:CrashLog maxTerminationResistance:Interactive>
Triggered by Thread:  0`

**Comment by weeeBox** [comment]
@flankechen, what plugin version have you been using?

**Comment by flankechen** [comment]
@weeeBox I try new v1.8.1 version. it's solved, thanks.
