### ISSUE TITLE
Missing messages when sharing log

### ISSUE THREAD

**Issue by diegoleao** [SpaceMadness/lunar-unity-console#191]
Hi! Our clients are accustomed to using Lunar Console by now, "**but**" some of them learned to filter the log messages, for example, to only view the errors. Certainly a useful feature for them. 

But when we ask them to share their logs via e-mail, we have to strongly emphasize that they do must NOT turn anything off visually, even warnings. But sometimes they forget, leading to big problems.

As I understand it, turning off warnings, logs, errors should only affect Lunar Console _visually_ (as a way for the user to organize things and be more efficient).

But when sharing/copying the log, it is _essencial_ that we get everything, we can't afford missing messages. Recently we were tracking a bug that was very difficult to reproduce, and we lost a lot of time since essencial warnings were turned off inadvertently, leading to confusion, since it appeared as if a module was not executing.

I believe Lunar Console is great for internal tests, and we never had this kind of problem before "exposing" it to our clients. But now that distributed clients are sharing logs that we can't really "trust", it became a big problem.

Sorry if this message is too long, I didn't think I could explain it well with less words.

Can you help me change this behaviour?
Thank you

**Comment by weeeBox** [comment]
Fixed in 1.8.3
