### ISSUE TITLE
Unity 2020.3 LTS

### ISSUE THREAD

**Issue by re-cheid** [SpaceMadness/lunar-unity-console#192]
Just upgraded to Unity 2020.3.0 f1 LTS version, and it seems that the `CallbackFunction` definition in `AndroidPlugin.cs` need to be adjusted again.

Currently it is:
```
#if UNITY_2020_1_OR_NEWER
using CallbackFunction = System.Action;
#else
using CallbackFunction = UnityEditor.EditorApplication.CallbackFunction;
#endif
```

which causes compile errors, found that the `UnityEditor.EditorApplication.CallbackFunction` definition works with that unity version

**Comment by weeeBox** [comment]
Hi @re-cheid,

I'll take a look - thanks for reporting!

**Comment by weeeBox** [comment]
@re-cheid, everything builds fine on both mac and windows - can you confirm you still facing the issue?

**Comment by re-cheid** [comment]
Hi, sorry for the late response.

I checked it again with Unity 2020.0.9 LTS and the latest version of lunar console pro. 
The issue seems to be gone now.

**Comment by Bobby-RobertQ** [comment]
can i get someone to check that this didnt just happen again in 2020.3.25f1 
#if UNITY_2020_1_OR_NEWER
