### ISSUE TITLE
iOS build error: pngcrush caught libpng error:    Not a PNG file..

### ISSUE THREAD

**Issue by Stephan-FDG** [SpaceMadness/lunar-unity-console#193]
Hello,

i have a problem with the iOS build and I was hoping you could help me out
Main problem here is, that even though the archive is created and I could manually upload it, the problem is that Jenkins marks this as a build error and stops the deploy process.

Here is the Error Message:
All Images from "/LunarConsole/Editor/iOS/Common/Images" are affected I am getting a total of 115 Errors
<details><summary>Xcode Error</summary>
<p>
While reading /Users/buildmachine/.jenkins/workspace/myApp/Assets/External/LunarConsole/Editor/iOS/Common/Images/lunar_console_actions_empty_warning.png pngcrush caught libpng error:
   Not a PNG file..

Could not find file: /Users/buildmachine/Library/Developer/Xcode/DerivedData/Unity-iPhone-cbzbsuhxundvzwegfytpipsbsjlx/Build/Products/Debug-iphoneos/myApp.app/lunar_console_actions_empty_warning.png
Command /Applications/Xcode.app/Contents/Developer/usr/bin/copypng emitted errors but did not return a nonzero exit code to indicate failure
</p>
</details>

Unity Version: 2020.2.3f1
We are building on BigSur on a M1 Chip 

I tried to update LunarConsole with no success.

I already set the PNG Compress to "NO" in our post-build script with this command:
`pbxProject.SetBuildProperty(targetGuid,"COMPRESS_PNG_FILES","NO");`

did I miss any Settings?
Thanks in advanced!

**Comment by weeeBox** [comment]
Hi @Stephan-FDG - I haven't seen this before: what's Xcode version do you use? Can you attach the whole log?

**Comment by Stephan-FDG** [comment]
Hey, 
i was able to track down the issue. 
For some reason our Jenkins had issues with the git-lfs installation resulting in corrupting all .pngs from the repository.
this became clear after I tried to upload to TestFlight manually.

Updating git-lfs and telling Jenkins the correct path in the environment variables fixed my problem

But it had nothing to do with the lunar console, sorry for bothering you.

**Comment by weeeBox** [comment]
No worries - glad you figured it out!
