### ISSUE TITLE
Show console only on Gesture

### ISSUE THREAD

**Issue by kenofori** [SpaceMadness/lunar-unity-console#199]
Hi there,

I'm showing a lot of logs, and console appears automatically in footer,
I only want to show console on swipe gesture. 

How can I achieve that?
I own pro version.

Thanks

**Comment by weeeBox** [comment]
Hello,

You can disable the popup in the prefab settings:
![Screen Shot 2021-06-01 at 1 56 10 PM](https://user-images.githubusercontent.com/786644/120369363-25a60700-c2e1-11eb-90a3-b1fcb58ad46f.png)

**Comment by kenofori** [comment]
@weeeBox Tanks for your prompt reply,
Just so i'm clear, setting displaly mode to none will not show console on errors etc
BUT if i do swipe down, then ill see the console, right? (as this is what i want to achieve)

**Comment by weeeBox** [comment]
Correct - let me know if that works.
