### ISSUE TITLE
Rich text (color) does not apply to entire output

### ISSUE THREAD

**Issue by TechCor8** [SpaceMadness/lunar-unity-console#203]
The rich text output does not match the Unity editor output. This behavior may be due to the log length.

We use StringBuilder to append a large number (50+) of color coded variables together. The first few lines display correctly, but then the color tags are ignored.

Example code:
```
System.Text.StringBuilder sb = new System.Text.StringBuilder();
foreach (var item in List)
{
    string color = item.IsSet ? "00ff00ff" : "007700ff";
    sb.AppendLine($"<color=#{color}>" + item.Name + "</color> = <color=#ffffffff>" + item.ToString() + "</color>");
}

Debug.Log(sb.ToString());
```

**Comment by weeeBox** [comment]
Fixed in 1.8.6
