### ISSUE TITLE
How to turn off automatic notifications,plz

### ISSUE THREAD

**Issue by 1328649047** [SpaceMadness/lunar-unity-console#221]
How to turn off automatic notifications,plz
![image](https://github.com/user-attachments/assets/4adc61c7-f9e9-4934-8f1e-2ef877e333e1)

**Comment by 1328649047** [comment]
I want to turn off "Instant error notification"

**Comment by Whitebrim** [comment]
![image](https://github.com/user-attachments/assets/9f23875f-4245-4a52-88d2-4b6bebde0cc2)

**Comment by 1328649047** [comment]
> ![图像](https://private-user-images.githubusercontent.com/23287829/373637083-9f23875f-4245-4a52-88d2-4b6bebde0cc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDUyNjgsIm5iZiI6MTczMDM0NDk2OCwicGF0aCI6Ii8yMzI4NzgyOS8zNzM2MzcwODMtOWYyMzg3NWYtNDI0NS00YTUyLTg4ZDItNGI2YmViZGUwY2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAzMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwODFjM2Q2ZDhiYWE1ZDZjYzRkOTU1MTIyYjZhZWVjYjUzNjFkYTY4ZWZkYjUwNDdkZjZjMWIwYjVlODAzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lax4nkErw5pFGYOYu96m2X0HEUbvu2SOfvtYTTKkSFA)

tanks，bro
