### ISSUE TITLE
"Local reference table overflow" in android

### ISSUE THREAD

**Issue by jinunpark** [SpaceMadness/lunar-unity-console#31]
Hi. I'm using lunar console in my game.

Unity version is 5.3.5f1.

In iOS, lunar is fine. It's very good to see and search logs. Thanks!

But when I applied lunar in Android, it makes error below:

```
art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
art/runtime/indirect_reference_table.cc:115] local reference table dump:
art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
art/runtime/indirect_reference_table.cc:115]       511: 0x143de000 java.lang.String "2017-01-11,13:49... (1275 chars)
art/runtime/indirect_reference_table.cc:115]       510: 0x1410ac40 java.lang.String ""
art/runtime/indirect_reference_table.cc:115]       509: 0x143dd000 java.lang.String "2017-01-11,13:49... (1276 chars)
art/runtime/indirect_reference_table.cc:115]       508: 0x1410ac30 java.lang.String ""
art/runtime/indirect_reference_table.cc:115]       507: 0x143dc000 java.lang.String "2017-01-11,13:49... (1273 chars)
art/runtime/indirect_reference_table.cc:115]       506: 0x1410ac20 java.lang.String ""
art/runtime/indirect_reference_table.cc:115]       505: 0x143db000 java.lang.String "2017-01-11,13:49... (1275 chars)
art/runtime/indirect_reference_table.cc:115]       504: 0x1410ac10 java.lang.String ""
art/runtime/indirect_reference_table.cc:115]       503: 0x143da000 java.lang.String "2017-01-11,13:49... (1271 chars)
art/runtime/indirect_reference_table.cc:115]       502: 0x1410ac00 java.lang.String ""
art/runtime/indirect_reference_table.cc:115]   Summary:
art/runtime/indirect_reference_table.cc:115]         1 of com.unity3d.player.UnityPlayer$b
art/runtime/indirect_reference_table.cc:115]       511 of java.lang.String (511 unique instances)
art/runtime/indirect_reference_table.cc:115] 
```

It seems about log string is too many to handle. But without lunar, it's not appear.

Can I get information for find cause of this problem?

**Comment by weeeBox** [comment]
Hello,

Can you try to create an empty project, integrate the plugin and see if the issue still occurs?

Please, refer to the [Troubleshooting](https://github.com/SpaceMadness/lunar-unity-console/wiki/Troubleshooting#before-you-start) guide for more info:

**Comment by jinunpark** [comment]
Ok. I'll try step on troubleshooting and report in weekend.

**Comment by weeeBox** [comment]
Thanks! It would be helpful if you can provide the list of other Android plugins used in you project.

**Comment by jinunpark** [comment]
Roger that. :)

**Comment by jinunpark** [comment]
Sorry. I'm late.

I made empty project and added lunar console.

And added LunarCondsole GameObject by install LunarConsole,
<img width="324" alt="2017-01-16 3 44 32" src="https://cloud.githubusercontent.com/assets/9670638/21973275/ce2b5828-dc02-11e6-9876-f7040f7bc32e.png">

Asset is only:
<img width="447" alt="2017-01-16 3 44 38" src="https://cloud.githubusercontent.com/assets/9670638/21973276/ce360890-dc02-11e6-9ae4-4a2f0150aa71.png">

And added LogMaker to write log per frame.
<img width="364" alt="2017-01-16 3 44 46" src="https://cloud.githubusercontent.com/assets/9670638/21973274/ce2a900a-dc02-11e6-8336-1eef98d7d92a.png">

And LogMaker is:
```csharp
using UnityEngine;
using System.Collections;

public class LogMaker : MonoBehaviour {
	
	static readonly int LOG_COUNT_PER_FRAME = 253;

	// Use this for initialization
	void Start () {
	
	}
	
	// Update is called once per frame
	void Update () {
		for (int i = 0; i < LOG_COUNT_PER_FRAME; ++i)
		{
			Debug.Log("test");
		}
	}
}
```

And when I change LOG_COUNT_PER_FRAME to 254, app is crashed on phone.

Crash message is about "Local reference table overflow" too.

Unity version is 5.3.5f1.
Script build option is mono2x.
Minimum API level is 9.
Api compatiblity level is .NET 2.0 subset.
Android test device is SM-G906S, kernel version is 3.10.40-9635849.

**Comment by jinunpark** [comment]
Sorry. I missed Android version. It's 6.0.1.

**Comment by weeeBox** [comment]
Thanks, @jinunpark! I'll take a look asap!

**Comment by weeeBox** [comment]
@jinunpark, the bug is fixed now: I'm able to run the app with 500 logs per frame and it does not crash. The changes would appear in the next release (would take around 10 days to pass through).

In a mean time, take a look at this [pull request](https://github.com/SpaceMadness/lunar-unity-console/pull/32). All you need to do is to download an updated file [LunarConsole.cs](https://github.com/SpaceMadness/lunar-unity-console/blob/develop/Project/Assets/LunarConsole/Scripts/LunarConsole.cs) and replace the old one at **Assets/LunarConsole/Scripts/LunarConsole.cs** with it.

Thanks again for finding this bug!

-Alex

**Comment by jinunpark** [comment]
Thank you for bug fix! @weeeBox

**Comment by weeeBox** [comment]
Sure! Thanks for reporting it! Don't forget to rate the plugin if you find it useful :)
