### ISSUE TITLE
Crash on Unity Open Project

### ISSUE THREAD

**Issue by tucano** [SpaceMadness/lunar-unity-console#35]
Hello, with the new project on OSX 10.11.6 the Unity project sometimes crash on compilation of scripts. If I remove the Lunar console from the asset the projectdoes not crash and I can reimport the Lunar console with the project open.

Any idea where I can get a crash log? Unity/Editor.log seems not reporting anything of interesting.

**Comment by weeeBox** [comment]
Hey there!

Sorry for the issue. What Unity version do you use? Does it crash on an empty project? Are there any other plugins?

**Comment by tucano** [comment]
Unity version 5.5.0f3 

Is my main project so there are several other plugins, but I have experiencing this problem only after the importing of the Lunar Console.

Is quite scary: Unity project won't open but the fix is simple, I remove lunar from assets and I reimport it.

I have in plugins/Android/LunarConsole the following included platforms:
- Android
-OSX

The project is currently in Android Mode.

When I have the time I can test with an empty project. Any idea of which log I have to check? Editor.log?

Thanks for the quick response!

**Comment by weeeBox** [comment]
Thanks for the info.

It's hard to tell right now but can you try to remove all Unity temp files? If you're on git use `git clean -x -f -d` in your project's root (**make sure all project files are checked in and committed**). If you don't use git - remove the following files:
```
/Library
/Temp
/Obj
/Build
/Builds/

/.vs

ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
```
Let me know if it helps

**Comment by weeeBox** [comment]
I did a quick test with Lunar Mobile Console v0.9.0 on Unity 5.5.0f3 Personal (OS X 10.12.1): everything compiles and runs fine. 

You can also look at the [Troubleshooting](https://github.com/SpaceMadness/lunar-unity-console/wiki/Troubleshooting#before-you-start) guide on wiki for proper "clean up" steps.

I haven't found match on the editor logs besides [Log Files](https://docs.unity3d.com/Manual/LogFiles.html) and [Editor Troubleshoot](https://docs.unity3d.com/Manual/TroubleShootingEditor.html) documentation. If the problem persists on an empty project - please zip it and send to me for further investigation.

Thanks for reporting the issue!

**Comment by tucano** [comment]
Hello I am here again with the morning crash.

git clean -x -f -d did the job. 

And the project was reimported and is up and running, let's see what open tomorrow :-)

**Comment by weeeBox** [comment]
Hello!

Great to hear that! I'll update the troubleshooting guide.

Thanks for your help!

**Comment by weeeBox** [comment]
Please, let me know if this approach resolves the bug so I can close the issue
