### ISSUE TITLE
API Calls are undocumented

### ISSUE THREAD

**Issue by JanOschii** [SpaceMadness/lunar-unity-console#39]
Hi guys, 

you have a link in your documentation (under "Usage") that leads to an non existing "API Calls" documentation.

> You can open the console with a multi touch gesture or using the API call from a script (see API Calls for details).

If someone else missing it and is reading this here.
You should take a look in the LunarConsole Component Script (LunarConsole.cs) to find all functions.

To open the console from script: LunarConsolePlugin.LunarConsole.Show();

Jan

PS: Nice asset! Very useful. 
PPS: Also the link to the asset store is wrong.
PPPS: You should think about a version that runs in VR.

**Comment by weeeBox** [comment]
Hi Jan!

Thanks for finding those issues! Everything is fixed now.

-Alex

p.s. don't forget to [rate](https://www.assetstore.unity3d.com/en/#!/account/downloads/search=Lunar%20Mobile%20Console) the plugin on the Asset Store if you find it useful!
