### ISSUE TITLE
Change default setting value in source code

### ISSUE THREAD

**Issue by Seromu** [SpaceMadness/lunar-unity-console#48]
Thnak you for great tool!
Our team using this asset, and several designer and artist request 'changing default setting' when application installed. Can I change this with API?

Setting
- Enable Exception Warning
- Enable Transparent Log

**Comment by weeeBox** [comment]
Thanks, @Seromu. I'll add the features you've requested into the next release

**Comment by Seromu** [comment]
Thank you! :+1:

**Comment by weeeBox** [comment]
Hi, @Seromu!

Sorry it took so long (Unity 5.6 release was tough) but I finally addressed both of your issues (https://github.com/SpaceMadness/lunar-unity-console/issues/48 and https://github.com/SpaceMadness/lunar-unity-console/issues/45). It usually takes 3-5 days for the package update to propagate on the asset store. Send me an [email](mailto:lunar.plugin@gmail.com)  and I'll send you the updated package.

**Comment by Seromu** [comment]
Great! I'll wait for update on asset store. Thank you! :+1:
