### ISSUE TITLE
Wrong layout with large log message on iOS

### ISSUE THREAD

**Issue by eandropov** [SpaceMadness/lunar-unity-console#50]
Hello, i have some layout issues on iOS with large log message. [Screenshot](http://take.ms/4uMiB) from iphone7.
Also, i set "Default Orientation" in unity player settings to "Auto Rotation" and check only landscape right/left, but console can be rotated into any orientation.

**Comment by weeeBox** [comment]
Hi, Evgeny.

Sorry for the issue. I'll take a look at it asap and get back to you!

-Alex

**Comment by weeeBox** [comment]
Please, update source files according to the pull request: https://github.com/SpaceMadness/lunar-unity-console/pull/51.  
Asset Store update is still pending.

**Comment by eandropov** [comment]
Thx, it works well on ios, but i found same issue on android too

**Comment by weeeBox** [comment]
I've opened another ticket for it: https://github.com/SpaceMadness/lunar-unity-console/issues/52

Thanks for reporting.

**Comment by weeeBox** [comment]
@eandropov, Android issue is fixed: https://github.com/SpaceMadness/lunar-unity-console/issues/52
