### ISSUE TITLE
Is Editor support planned?

### ISSUE THREAD

**Issue by Myrtanim** [SpaceMadness/lunar-unity-console#58]
Is there anything planned to get the console also running in the editor in playmode? Especially the Actions and Variables part?

**Comment by weeeBox** [comment]
Yes. It's in the roadmap

**Comment by Myrtanim** [comment]
Can you give a rough ETA when this will happen?

**Comment by weeeBox** [comment]
At least 1 weak

**Comment by Myrtanim** [comment]
Ok, thanks, waiting eagerly to happen for this!
And keep up the great work, this is a really great tool!

**Comment by weeeBox** [comment]
Thanks. I'll keep you posted.

**Comment by weeeBox** [comment]
@Myrtanim, you can track the progress here: https://github.com/SpaceMadness/lunar-unity-console/pull/59

**Comment by weeeBox** [comment]
Available in [v1.4.0](https://github.com/SpaceMadness/lunar-unity-console/releases/tag/1.4.0)

**Comment by Myrtanim** [comment]
Oh, wow that was quick, thank you very much! Will test this out today.

**Comment by weeeBox** [comment]
Sure! The package update is still pending (might take 3-5 days to fall through). You can update your files according to the [pull request](https://github.com/SpaceMadness/lunar-unity-console/pull/59) or send me an email and I'll send you the package.
