### ISSUE TITLE
Release 1.4.0 not compilable for Android

### ISSUE THREAD

**Issue by Myrtanim** [SpaceMadness/lunar-unity-console#60]
Hi, with the recent 1.4.0 release I can't build Android versions anymore. I get compiler errors for `LunarConsole.cs`

![image](https://cloud.githubusercontent.com/assets/1941740/25523412/e2827956-2c06-11e7-8233-a9773e6f53b9.png)

**Comment by weeeBox** [comment]
Confirmed. The on-device testing was scheduled for today. The package usually gets tested while pending on the Asset Store (saves a few days for production).

**Comment by weeeBox** [comment]
@Myrtanim, here's PR for the issue: https://github.com/SpaceMadness/lunar-unity-console/pull/61. I'm going to do more testing before releasing. Feel free to update files and give it a try.

**Comment by weeeBox** [comment]
@Myrtanim, the issue has been addressed. New update is pending.

**Comment by weeeBox** [comment]
@Myrtanim, 1.4.0 is now live on the Asset Store

**Comment by Myrtanim** [comment]
Hey @weeeBox, thanks for this info, implementation is almost done in my project and it's working really great, thank you!

**Comment by weeeBox** [comment]
Great! Let me know if you have any questions!

p.s. don't forget to rate the plugin on the Asset Store if you find it useful
