### ISSUE TITLE
Can't not import 'lunar-console.aar' file.

### ISSUE THREAD

**Issue by Seromu** [SpaceMadness/lunar-unity-console#63]
```
Can't enable Android plugin: unable to create importer for 'Assets/LunarConsole/Editor/Android/lunar-console.aar'. Re-install Lunar Mobile Console to fix the issue.
UnityEngine.Debug:LogErrorFormat(String, Object[])
LunarConsoleEditorInternal.AndroidPlugin:SetEnabled(Boolean) (at Assets/LunarConsole/Editor/AndroidPlugin.cs:48)
LunarConsoleEditorInternal.Autorun:.cctor() (at Assets/LunarConsole/Editor/Autorun.cs:53)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()
```

I can't import Lunar Mobile Console PRO v1.4.0 even in new empty project(Unity 5.6.0f3).
I tried removing asset cache and retry download, but it didn't work.
(Cache path C:\Users\[USERNAME]\AppData\Roaming\Unity\Asset Store-5.x\SpaceMadness)

**Comment by weeeBox** [comment]
Hi @Seromu,

Sorry for the issue. I'm not able to reproduce it right now. Let me check a few more things and I'll get back to you.

**Comment by weeeBox** [comment]
@Seromu, I haven't fully tested it yet but it seems to be a path issue. Please, look at this [pull request](https://github.com/SpaceMadness/lunar-unity-console/pull/64) and let me know if it works for you

**Comment by weeeBox** [comment]
Patch file: [lunar-console-patch-1.4.1.unitypackage](https://github.com/SpaceMadness/lunar-unity-console-patches/raw/master/lunar-console-patch-1.4.1.unitypackage)

**Comment by Seromu** [comment]
Thank you for your feedback!
I'll check this next week! XD

2017/05/03 10:55、Alex Lementuev <notifications@github.com> のメッセージ:

**Comment by weeeBox** [comment]
@Seromu, v1.4.1 is now live on the Asset Store

**Comment by Seromu** [comment]
Thanks a lot! I'll adapt it on Asset Store(now you can remove patch file) XD

**Comment by Snow-Okami** [comment]
I am having this same issue with the Pro version from the asset store: 1.51 - Unity 5.6.4. Any suggestions?

**Comment by weeeBox** [comment]
@Snow-Okami, usually deleting/re-importing the plugin fixes the issue.

**Comment by Snow-Okami** [comment]
I have tried this multiple times but it seems I always get the error. (Windows 10, with Android SDK, NDK and JRE installed) I installed the patch posted earlier up over my 1.51 installation and now I get a second error in Autorun.cs in the LegacyAsset function. Seems to still work on my android device though. I commented out the line that runs that function.

**Comment by weeeBox** [comment]
@Snow-Okami, sorry for the issue. I'll take a closer look.

**Comment by nicloay** [comment]
Have the same problem with pro version on unity 2018.3.3f1 tried to reinstall several times with no luck. I have several version of unity installed on my mac, and 2018 is located at not default folder (/Applications/Unity2018/...)

**Comment by weeeBox** [comment]
@nicloay, the importer throws an exception but still able to properly import the aar file. I have no idea how to fix it but the console seems to be working fine!

**Comment by Nathanovic** [comment]
I also have this issue, tried deleting the LunarConsole folder and re-importing. Didn't work. Any way to fix this error?

**Comment by weeeBox** [comment]
@Nathanovic, does the plugin work on Android?

**Comment by Nathanovic** [comment]
@weeeBox Excuse me. Re-importing actually did work, but I had to restart Unity first! 
The plugin works fine on Android.
