### ISSUE TITLE
LunarConsole enforces READ_PHONE_STATE on Android

### ISSUE THREAD

**Issue by Myrtanim** [SpaceMadness/lunar-unity-console#67]
Hi,

our game is asking on Android devices for the permission to do phone calls when Lunar is integrated.
This is because of your integrated analytics and it's usage of `UnityEngine.SystemInfo.deviceUniqueIdentifier`, which in turn causes Unity to automatically add  `android.permission.READ_PHONE_STATE` to the Android Manifest.

We don't use Lunar in release builds, but still it shocked our testers first and this pushes our development builds further away from the Live state, because the build process is indirectly modified with this additional permission.

Is using the device ID really necessary? Can't you just switch to the [advertisement ID](https://docs.unity3d.com/ScriptReference/Application.RequestAdvertisingIdentifierAsync.html) or remove this completely on mobile?

**Comment by weeeBox** [comment]
Hey @Myrtanim,

Let me look at it really quick and I'll get back to you

**Comment by weeeBox** [comment]
@Myrtanim,

When I create an empty project with Lunar Mobile Console integrated there's no `android.permission.READ_PHONE_STATE` permission in the generated `AndroidManifest.xml` file:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.spacemadness.LunarConsoleTest" xmlns:tools="http://schemas.android.com/tools" android:versionName="1.0" android:versionCode="1" android:installLocation="preferExternal">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <application android:theme="@style/UnityThemeSelector" android:icon="@drawable/app_icon" android:label="@string/app_name" android:isGame="true" android:banner="@drawable/app_banner">
    <activity android:label="@string/app_name" android:screenOrientation="fullSensor" android:launchMode="singleTask" android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale|layoutDirection" android:name="com.spacemadness.LunarConsoleTest.UnityPlayerActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
  </application>
  <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="25" />
  <uses-feature android:glEsVersion="0x00020000" />
  <uses-feature android:name="android.hardware.vulkan" android:required="false" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="18" />
  <uses-feature android:name="android.hardware.touchscreen" android:required="false" />
  <uses-feature android:name="android.hardware.touchscreen.multitouch" android:required="false" />
  <uses-feature android:name="android.hardware.touchscreen.multitouch.distinct" android:required="false" />
</manifest>
```
Can you try to reproduce this behavior on a 'fresh' project? Are there any plugins or Android-specific APIs in the debug version of your project. Would this behavior be reproduced if you disable Lunar Mobile Console in a debug build?

**Comment by Myrtanim** [comment]
Hey @weeeBox, I did some test and can still reproduce it but found some interesting Unity behaviour.

But first my setup (maybe this also matters), I'm using:
* IL2CPP
* .NET 2.0 (*not* subset)
* Development Build in Unity Build Settings
* Lunar Mobile Console PRO 1.4.0

What I actually found out is that it seems to depend on the Unity version.
With **5.3.6p8** I get the following `AndroidManifest.xml`, which contains `android.permission.READ_PHONE_STATE`:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="preferExternal" package="com.innogames.lunartest" platformBuildVersionCode="25" platformBuildVersionName="7.1.1">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:smallScreens="true" android:xlargeScreens="true"/>
    <application android:banner="@drawable/app_banner" android:debuggable="true" android:icon="@drawable/app_icon" android:isGame="true" android:label="@string/app_name" android:theme="@style/UnityThemeSelector">
        <activity android:configChanges="locale|fontScale|keyboard|keyboardHidden|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode" android:label="@string/app_name" android:launchMode="singleTask" android:name="com.unity3d.player.UnityPlayerActivity" android:screenOrientation="fullSensor">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <category android:name="android.intent.category.LEANBACK_LAUNCHER"/>
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true"/>
        </activity>
        <activity android:name="spacemadness.com.lunarconsole.settings.SettingsActivity"/>
    </application>
    <uses-feature android:glEsVersion="0x00020000"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:maxSdkVersion="18" android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-feature android:name="android.hardware.touchscreen" android:required="false"/>
    <uses-feature android:name="android.hardware.touchscreen.multitouch" android:required="false"/>
    <uses-feature android:name="android.hardware.touchscreen.multitouch.distinct" android:required="false"/>
</manifest>
```
This is, when Lunar is enabled. If I disable it the permission is not requested.

But if I use **5.4.4p3** the manifest does not contain the permission, independent if the console is enabled or not.

If I wrap up the `SystemInfo.deviceUniqueIdentifier` in `#if UNITY_5_4_OR_NEWER` I also don't get the permission in 5.3.6p8 builds but of course then there is no device ID for your analytics.

Currently we can't upgrade to any other Unity version.

Greetings
Myrtanim

**Comment by weeeBox** [comment]
Thanks for the info, @Myrtanim. I'll take a look!

**Comment by weeeBox** [comment]
@Myrtanim, [1.4.2](https://github.com/SpaceMadness/lunar-unity-console-patches/raw/master/lunar-console-patch-1.4.2.unitypackage) patch is now available.

You can disable analytics by using `LUNAR_CONSOLE_ANALYTICS_DISABLED` preprocessor define: https://docs.unity3d.com/Manual/PlatformDependentCompilation.html
