### ISSUE TITLE
Wrong orientation on iOS 8.1.3

### ISSUE THREAD

**Issue by eandropov** [SpaceMadness/lunar-unity-console#69]
Hello there. I found an orientation issue on iOS 8.1.3 and lower, can be reproduced on Unity 5.5.3f1 with "Auto Rotation" orientation setting and landscape right/left toggles. [Screenshot1](http://take.ms/QxT3h), [Screenshot2](http://take.ms/VTpbq) from ipad mini 2.

**Comment by weeeBox** [comment]
Hey @eandropov! Thanks for reporting, I'll take a look at it.

**Comment by weeeBox** [comment]
iOS 8 is no longer supported
