### ISSUE TITLE
Error: Stale Touch Detected! on multitouch iOS

### ISSUE THREAD

**Issue by ngrigoryev** [SpaceMadness/lunar-unity-console#70]
Hello!
How to reproduce:
Create unity project with Lunar implemented.
Create canvas with render mode Screen space - overlay.
Create any image under canvas.
Create default event System.
Build for iOS and deploy on device. iOS 10.3.2 and 10.1.1, Unity 5.5.3f1 or 5.5.6p2 or 5.5.1p3.
In runtime place one finger on image and start tapping by second. There will be error:
Stale touch detected!
(Filename: /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/iPhoneInputImpl.mm Line: 396)

It is not reproducable without Lunar or with disabled Lunar.

**Comment by weeeBox** [comment]
Hi @ngrigoryev! Thanks for reporting, I'll take a look at it.

**Comment by ngrigoryev** [comment]
Hi! Have you reproduced it? 
If right solution is hard to achieve,  is it possible to customize messages to be warned/not warned about in console pop-up, so we can disable only this message for debug playtest stage? At this stage this pop-up is important to catch exception cases.

**Comment by weeeBox** [comment]
Hi, @ngrigoryev! I'll look at it later today. Sorry it's taking long.

**Comment by weeeBox** [comment]
It seems like there's an [issue](https://forum.unity3d.com/threads/stale-touch-detected.54074/) with CADisplayLink + CocoaTouch UI in Unity. Needs further investigation. For now, here's a patch which make the plugin ignore "stale touch" warnings.  
  
https://github.com/SpaceMadness/lunar-unity-console-patches/blob/master/lunar-console-patch-1.4.4.unitypackage

**Comment by ngrigoryev** [comment]
@weeeBox Thank you for your support :) 👍

**Comment by weeeBox** [comment]
Sure! Don't forget to [rate and review](https://www.assetstore.unity3d.com/en/#!/account/downloads/search=Lunar%20Mobile%20Console) the plugin on the Asset Store if you find it useful!
