### ISSUE TITLE
NSRangeException at LUMutableArray.m:73

### ISSUE THREAD

**Issue by eandropov** [SpaceMadness/lunar-unity-console#72]
Hello there, i've got an exception on ios:

Fatal Exception: NSRangeException
0  CoreFoundation                 0x182d842d8 __exceptionPreprocess
1  libobjc.A.dylib                0x194a500e4 objc_exception_throw
2  CoreFoundation                 0x182c6785c -[__NSArrayM removeObjectAtIndex:]
3                             0x101bec7bc -[LUMutableArray objectAtIndex:] (LUMutableArray.m:73)
4                             0x101c183e4 -[LUConsoleLogEntryList entryAtIndex:] (LUConsoleLogEntryList.m:116)
5                             0x101c17580 -[LUConsole entryAtIndex:] (LUConsole.m:51)
6                             0x101bb4c58 -[LUConsoleOverlayController lunarConsole:didAddEntryAtIndex:trimmedCount:] (LUConsoleOverlayController.m:115)
7                             0x101bb52d8 -[LUConsoleOverlayController lunarConsole:didUpdateEntryAtIndex:trimmedCount:] (LUConsoleOverlayController.m:144)
8                             0x101c178a0 -[LUConsole logMessage:stackTrace:type:] (LUConsole.m:77)
9                             0x101bd27bc __46-[LUConsolePlugin logMessage:stackTrace:type:]_block_invoke (LUConsolePlugin.m:190)
10                            0x101be3674 lunar_dispatch_main (LUThreading.m:34)
11                            0x101bd26f8 -[LUConsolePlugin logMessage:stackTrace:type:] (LUConsolePlugin.m:188)
12                            0x101c25f9c __lunar_console_log_message (lunar_unity_native_interface.m:91)

**Comment by weeeBox** [comment]
Hey, @eandropov.

Sorry for the issue! 

- What is the console's capacity and the trim size? 
- How often this crash happens? Do you have any specific reproduction steps?
- Do you have multiple threads in your game?

**Comment by weeeBox** [comment]
Fixed in 1.4.5
