### ISSUE TITLE
onConsoleClosed not called when closing console with LunarConsolePlugin.LunarConsole.Hide();

### ISSUE THREAD

**Issue by LeoToivio** [SpaceMadness/lunar-unity-console#78]
Hello!

I found a bug. `LunarConsolePlugin.LunarConsole.onConsoleClosed` is not called when closing console with `LunarConsolePlugin.LunarConsole.Hide();`.

I did a workaround by calling the action assigned to 
`LunarConsolePlugin.LunarConsole.onConsoleClosed` right after hiding the console so no worries.

**Comment by weeeBox** [comment]
Hey @LeoToivio,

Sorry for the issue. I'll take a look at it.
